# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_auto_20180324_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='some clever words here'),
        ),
    ]
